apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynamic-target-beacon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: dynamic-target-beacon
  namespace: my-namespace